# Generated by Django 5.1.1 on 2024-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_transaction_terms_transaction_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="terms_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
